# payment-service/.github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:


jobs:
  build-and-test:
    uses: jogeshniwalkar/devops_central/.github/workflows/build-and-test.yml@develop
    with:
      java_version: '17'